### ISSUE TITLE
w.local.get requires a type, but WAT local.get doesn't

### ISSUE THREAD

**Issue by trusktr** [judehunter/wazum#5]
Curious why `w.local.get` require a type (f.e. `"i32"`) while the WAT `local.get` doesn't. Is the added type doing something?

**Comment by judehunter** [comment]
This is done to follow the philosophy of "correctness over inference" that I set out for wazum.

Basically, you don't need it in WAT because the compiler can analyze the program statically to look up the local's type.

However for wazum, you want to have that at typecheck-time to achieve correctness. For instance, the following code will show an error:

```ts
w.add(
  'i32',
  w.local.get('i32', 'a'),  // ok!
  w.local.get('i64', 'b')  // err! Incompatible types i32 and i64
)
```

In the example above the mistake is obvious, but in more complex scenarios, the lack of a datatype for local.get would result in a spreading unsoundness.

That's one side of it. You might notice that that could be just a generic though, and not a parameter. There's some wiggle room here, but I think the goal would be to have a validator on the wazum side, for runtime. Not quite sure, open to suggestions.

Of course this all means that you need to maintain a type look up table for your IR and compiler, or something of sorts.

**Comment by trusktr** [comment]
Ah, thanks. That makes total sense is a nice feature!

> Of course this all means that you need to maintain a type look up table for your IR and compiler, or something of sorts.

Indeed we have a type system, so we'll be able to figure out which ARGS to pass in.



> You might notice that that could be just a generic though, and not a parameter. There's some wiggle room here, but I think the goal would be to have a validator on the wazum side, for runtime. Not quite sure, open to suggestions.

Will keep this in mind. I'll close this, and if I do come up with something, I can suggest in a new issue.
